Update file .gitlab-ci.yml

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -278,23 +278,25 @@ Img_scan_shippingservice:
 check_critical_errors:
   stage: check
   script:
-    - |
-      total_critical_errors=0
-      for file in *.txt; do
+    - total_critical_errors=0
+    - for file in *.txt; do
         critical_errors=$(grep -c "CRITICAL" "$file")
         echo "File: $file, Critical errors: $critical_errors"
+        if [ $critical_errors -gt 5 ]; then
+          echo "File $file has more than 5 critical errors. Failing the pipeline."
+          exit 1
+        fi
         total_critical_errors=$((total_critical_errors + critical_errors))
       done
-      echo "Total critical errors: $total_critical_errors"
-      if [ $total_critical_errors -gt 5 ]; then
+    - echo "Total critical errors: $total_critical_errors"
+    - if [ $total_critical_errors -gt 5 ]; then
         echo "Total critical errors exceed threshold. Failing the pipeline."
         exit 1
       fi
   artifacts:
     paths:
       - "*.txt"
-  allow_failure: true
-
+#  allow_failure: true
 
 
 
